version: '3'
services:
  web:
    image: nginx:1.15.6
    ports:
      - "7180:80"
    depends_on:
      - php
    volumes:
      - ../:/data2/home
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build: ./php
    depends_on:
      - postgres
    volumes:
    - ../:/data2/home
    - ./php/php_ini/php.ini:/usr/local/etc/php/php.ini
  postgres:
    image: postgres:10.1
    environment:
      POSTGRES_DATABASE: test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"